package utils;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.support.PageFactory;

import projectSpecifications.BaseClass;

public class ChatBotPrompts extends BaseClass{
	
	  private ThreadLocal<WebDriver> driver = new ThreadLocal<>();
	  
	public ChatBotPrompts(WebDriver driver) {
		 this.driver.set(driver);
	        PageFactory.initElements(driver, this);
	}

	   public Object[] getChatBotPrompts() {
	Object[] prompts = {
		    "I'm feeling a bit stressed today. Do you have any tips for relaxation?",
		    "Sure, what can I do to start my day positively?",
		    "Yes, that sounds good. What else can I do during the day?",
		    "I’ll give that a try. Any other techniques for physical relaxation?",
		    "That sounds helpful. What about taking breaks during the day?",
		    "I’ve heard about visualization techniques. How do they work?",
		    "I’m also interested in yoga. Any suggestions?",
		    "These all sound like great ideas. Thank you!",
		    "I need some advice on professional support. What can I do to feel more supported at work?",
		    "How can I collaborate better with my colleagues?",
		    "That sounds helpful. What about mentorship?",
		    "I’d like to improve my stress management skills. Any suggestions?",
		    "Are there any peer support groups I can join?",
		    "What if I feel like I need more help than that?",
		    "I’m struggling to balance work and personal life. Any tips?",
		    "Are there any online communities I can join?",
		    "What about wellness programs?",
		    "These suggestions are really helpful. Thanks!",
		    "Hello!",
		    "Good morning!",
		    "Hi!",
		    "How's the weather today?",
		    "How are you doing today?",
		    "What's your name?",
		    "Did you watch the cricket match last night?",
		    "What’s your favorite movie?",
		    "What’s the capital of India?",
		    "How many continents are there?",
		    "I'm feeling a bit tired today.",
		    "I have a lot of work to do.",
		    "Today is my Birthday",
		    "Tell me something interesting.",
		    "Give me a fun fact.",
		    "How is your day?",
		    "What is all there in the Dashboard?",
		    "What is a Class card?",
		    "It seems like there are no classes allocated to you.",
		    "What all you can do?",
		    "What all is available in the class/class page?",
		    "View class details.",
		    "How can I view the list of students?",
		    "What information can I see in the student list?",
		    "How can I view a student's details?",
		    "What is a cohort?",
		    "Where are the cohorts?",
		    "I want to see my cohorts?",
		    "Viewing a cohort.",
		    "I want to see the students in the cohort.",
		    "Editing a cohort.",
		    "I want to add more students to the cohort.",
		    "I want to add more content to the cohort",
		    "I want to remove content in my cohort",
		    "Deleting a cohort.",
		    "Auditing a cohort.",
		    "Create a custom cohort.",
		    "Create a predefined cohort.",
		    "Other actions.",
		    "What is Content?",
		    "How is the content categorized?",
		    "How is the content used?",
		    "What is Discovery Content?",
		    "Tell me a joke.",
		    "What's the meaning of life?",
		    "Can you tell me a story?",
		    "What's your favorite color?",
		    "What's your favorite book?",
		    "Do you like music?",
		    "What's your favorite food?",
		    "Do you have any hobbies?",
		    "What's the most interesting thing you've learned?",
		    "Can you do any impressions?",
		    "What day is it today?",
		    "How's your day going?",
		    "Do you have any pets?",
		    "What's the best way to spend a weekend?",
		    "Can you give me a movie recommendation?",
		    "What's the time now?",
		    "Do you believe in ghosts?",
		    "What's your favorite season?",
		    "Can you help me with my homework?",
		    "What is a cohort?",
		    "Yes.",
		    "How do I add students to a cohort?",
		    "Yes, please.",
		    "What is the content used for?",
		    "Yes.",
		    "How can I view student performance?",
		    "Yes.",
		    "What is the Dashboard?",
		    "Yes.",
		    "How do I create a predefined cohort?",
		    "Yes.",
		    "Can I delete a student from a class?",
		    "Okay.",
		    "How do I audit a cohort?",
		    "Yes.",
		    "How do I add content to a cohort?",
		    "Yes.",
		    "How do I change the language of the interface?",
		    "Yes.",
		    "I feel stressed.",
		    "I'm feeling down today.",
		    "I'm really happy today!",
		    "I’m worried about my students.",
		    "I feel overwhelmed with work.",
		    "I'm having a hard time managing my time.",
		    "I’m feeling unappreciated.",
		    "I'm excited about my new project!",
		    "What are some interactive teaching methods I can use?",
		    "How can I make my lessons more engaging?",
		    "How do I encourage student participation?",
		    "What are some good ways to give feedback to students?",
		    "How can I tailor my lessons for individual students?",
		    "What are some fun extracurricular activities for students?",
		    "How can I make a strong classroom community?",
		    "What should I do to help a student who is struggling?",
		    "How can I improve my students' critical thinking skills?",
		    "What are some effective ways to teach complex concepts?",
		    "How do I assess student understanding effectively?",
		    "What are some innovative teaching methods I can try?",
		    "How can I integrate technology into my teaching?",
		    "How do I create an inclusive classroom environment?",
		    "What are some ways to keep up with the latest educational research?",
		    "How do I support students with different learning styles?",
		    "What strategies can I use to improve student engagement?",
		    "How can I effectively use data to improve my teaching?",
		    "How do I create a balanced curriculum?",
		    "What are some ways to motivate students?",
		    "How can I improve my lesson planning?",
		    "What are some effective classroom management techniques?"
		};
	return prompts;
	
	   }

}
